/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorLinksAssociatedOneOf, instanceOfErrorLinksAssociatedOneOf, ErrorLinksAssociatedOneOfFromJSON, ErrorLinksAssociatedOneOfFromJSONTyped, ErrorLinksAssociatedOneOfToJSON } from "./ErrorLinksAssociatedOneOf";

/**
 * @type ErrorLinksAssociated
 *
 * @export
 */
export type ErrorLinksAssociated = ErrorLinksAssociatedOneOf | string;

export function ErrorLinksAssociatedFromJSON(json: any): ErrorLinksAssociated {
    return ErrorLinksAssociatedFromJSONTyped(json, false);
}

export function ErrorLinksAssociatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorLinksAssociated {
    if (json === undefined || json === null) {
        return json;
    }
    return { ...ErrorLinksAssociatedOneOfFromJSONTyped(json, true), err_str: JSON.stringify(json, true) };
}

export function ErrorLinksAssociatedToJSON(value?: ErrorLinksAssociated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfErrorLinksAssociatedOneOf(value)) {
        return ErrorLinksAssociatedOneOfToJSON(value as ErrorLinksAssociatedOneOf);
    }
    if (typeof value == "string") {
        return JSON.parse(value);
    }

    return {};
}
